### ISSUE TITLE
TEQ considered as a conditional EQ instruction

### ISSUE THREAD

**Issue by HugoDGD** [TheTarados/AssDeb#2]
When using the instruction TEQ, the cond is set to 0x0. Which means that the flags won't be updated if the Z flag is 0.

The following arm code produces the adjacent machine code. We clearly see that TEQ and TEQEQ produces the same hexadecimal representation.

```arm
TEQ R0, R0        ; 0x01300000
TEQEQ R0, R0      ; 0x01300000
ADD R0, R0        ; 0xE0800000
ADDEQ R0, R0      ; 0x00800000
```

From the arm documentation(https://developer.arm.com/documentation/dui0473/m/arm-and-thumb-instructions/teq),  we see that the TEQ instruction supports the cond field and therefore should not be considered as a conditional instruction when found in its basic form.

**Comment by TEhhhA** [comment]
Indeed, this is not normal. I'll look into it and produce a patch as soon as possible.
