### ISSUE TITLE
RSB instruction not recognized

### ISSUE THREAD

**Issue by Felix-willaumez** [TheTarados/AssDeb#3]
Looks like the current release of AssDeb does not recognize the RSB instruction as when I use it in a code assdeb won't start reading the program and the .hex generated does not include any instruction for the rsb operation. Is it a predicted behavior or a bug ? Thanks in advance for the fix if it requires any.

**Comment by TEhhhA** [comment]
It was a simple argument missing for the rsb instruction. Thanks a lot for bringing it up to my attention. I'll do a release so that you can use RSB in your code.
